"use client";
import { useState, useEffect, use } from "react";
import { doc, onSnapshot } from "firebase/firestore";
import { db } from "@/lib/firebase";

/**
 * Live Preview Page - Renders App Blueprint
 *
 * This page renders a visual mockup of the app based on the blueprint
 * generated by the LLM. It updates in real-time as the build progresses.
 *
 * Blueprint structure (from src/lib/llmProvider.ts):
 * - appName: string
 * - target: "web" | "ios" | "android" | "multi"
 * - pages: Array<{ id, title, route, layout, sections }>
 * - dataModel: Array<{ name, fields }>
 * - authRequired: boolean
 */
export default function PreviewPage({ params }) {
  const [build, setBuild] = useState(null);
  const [loading, setLoading] = useState(true);
  const [selectedPage, setSelectedPage] = useState(null);

  // Unwrap async params in Next.js 15+
  const unwrappedParams = use(params);
  const buildId = unwrappedParams.buildId;

  // Real-time subscription to build document
  useEffect(() => {
    if (!buildId) return;

    const buildRef = doc(db, "builds", buildId);

    const unsubscribe = onSnapshot(
      buildRef,
      (snapshot) => {
        if (snapshot.exists()) {
          const buildData = { id: snapshot.id, ...snapshot.data() };
          setBuild(buildData);

          // Auto-select first page
          if (buildData.blueprint?.pages?.length > 0 && !selectedPage) {
            setSelectedPage(buildData.blueprint.pages[0]);
          }
        } else {
          setBuild(null);
        }
        setLoading(false);
      },
      (error) => {
        console.warn("Error loading build preview:", error);
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, [buildId, selectedPage]);

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900 flex items-center justify-center">
        <div className="text-center">
          <div className="w-16 h-16 border-4 border-purple-500/30 border-t-purple-500 rounded-full animate-spin mx-auto mb-4"></div>
          <p className="text-white/60 text-sm">Loading preview...</p>
        </div>
      </div>
    );
  }

  if (!build) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900 flex items-center justify-center p-8">
        <div className="text-center">
          <div className="w-20 h-20 mb-4 bg-red-500/20 rounded-full flex items-center justify-center mx-auto">
            <span className="text-4xl">⚠️</span>
          </div>
          <p className="text-white text-lg font-semibold mb-2">Build not found</p>
          <p className="text-white/60 text-sm">The requested build does not exist</p>
        </div>
      </div>
    );
  }

  // If blueprint not yet generated, show building state
  if (!build.blueprint) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-gray-900 flex items-center justify-center p-8">
        <div className="text-center max-w-md">
          <div className="w-20 h-20 mb-6 bg-gradient-to-br from-purple-500/20 to-blue-500/20 rounded-full flex items-center justify-center mx-auto animate-pulse">
            <span className="text-5xl">⚙️</span>
          </div>
          <h2 className="text-white text-2xl font-bold mb-3">
            Generating Blueprint...
          </h2>
          <p className="text-white/60 text-sm mb-6">
            {build.prompt}
          </p>
          <div className="w-full max-w-xs mx-auto space-y-3 animate-pulse">
            <div className="h-10 bg-white/10 rounded-lg"></div>
            <div className="h-24 bg-white/10 rounded-lg"></div>
            <div className="grid grid-cols-2 gap-2">
              <div className="h-20 bg-white/10 rounded-lg"></div>
              <div className="h-20 bg-white/10 rounded-lg"></div>
            </div>
          </div>
        </div>
      </div>
    );
  }

  const blueprint = build.blueprint;
  const currentPage = selectedPage || blueprint.pages[0];

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#0F172A] via-[#1E293B] to-[#0F172A] relative overflow-hidden">
      {/* Background decorations */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-0 left-1/4 w-96 h-96 bg-purple-600/10 rounded-full blur-3xl"></div>
        <div className="absolute bottom-0 right-1/4 w-96 h-96 bg-blue-600/10 rounded-full blur-3xl"></div>
      </div>

      {/* App Content */}
      <div className="relative z-10">
        {/* Top Bar / Navigation */}
        <nav className="bg-white/5 backdrop-blur-md border-b border-white/10 sticky top-0 z-50">
          <div className="max-w-6xl mx-auto px-6 py-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 bg-gradient-to-br from-purple-500 to-pink-500 rounded-xl flex items-center justify-center shadow-lg">
                  <span className="text-white text-xl font-bold">
                    {blueprint.appName.charAt(0).toUpperCase()}
                  </span>
                </div>
                <div>
                  <span className="text-white font-bold text-lg block">
                    {blueprint.appName}
                  </span>
                  <span className="text-white/50 text-xs">
                    {blueprint.target === "web" && "🌐 Web App"}
                    {blueprint.target === "ios" && "📱 iOS App"}
                    {blueprint.target === "android" && "🤖 Android App"}
                    {blueprint.target === "multi" && "🚀 Multi-Platform"}
                  </span>
                </div>
              </div>
              <div className="flex items-center gap-3">
                {blueprint.pages.slice(0, 3).map((page) => (
                  <button
                    key={page.id}
                    onClick={() => setSelectedPage(page)}
                    className={`px-4 py-2 text-sm font-medium transition-colors rounded-lg ${
                      currentPage.id === page.id
                        ? "bg-white/10 text-white"
                        : "text-white/70 hover:text-white hover:bg-white/5"
                    }`}
                  >
                    {page.title}
                  </button>
                ))}
                {blueprint.authRequired && (
                  <button className="px-4 py-2 bg-gradient-to-r from-purple-500 to-pink-500 text-white rounded-full text-sm font-semibold hover:scale-105 transition-transform shadow-lg">
                    Sign In
                  </button>
                )}
              </div>
            </div>
          </div>
        </nav>

        {/* Page Navigation Tabs (if more than 3 pages) */}
        {blueprint.pages.length > 3 && (
          <div className="bg-white/5 backdrop-blur-sm border-b border-white/10">
            <div className="max-w-6xl mx-auto px-6 py-2 flex gap-2 overflow-x-auto">
              {blueprint.pages.map((page) => (
                <button
                  key={page.id}
                  onClick={() => setSelectedPage(page)}
                  className={`px-4 py-2 text-sm font-medium transition-all rounded-lg whitespace-nowrap ${
                    currentPage.id === page.id
                      ? "bg-gradient-to-r from-purple-500/20 to-blue-500/20 text-white border border-white/20"
                      : "text-white/60 hover:text-white hover:bg-white/5"
                  }`}
                >
                  {page.title}
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Page Content */}
        <div className="max-w-6xl mx-auto px-6 py-12">
          {renderPageContent(currentPage, blueprint)}
        </div>

        {/* Data Model Info (bottom banner) */}
        {blueprint.dataModel && blueprint.dataModel.length > 0 && (
          <div className="fixed bottom-0 left-0 right-0 bg-white/5 backdrop-blur-md border-t border-white/10 p-3">
            <div className="max-w-6xl mx-auto flex items-center gap-3 text-xs text-white/50">
              <span className="font-semibold">🗄️ Data Model:</span>
              {blueprint.dataModel.slice(0, 5).map((entity, i) => (
                <span key={i} className="px-2 py-1 bg-white/5 rounded">
                  {entity.name} ({entity.fields.length})
                </span>
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

/**
 * Render page content based on layout and sections
 */
function renderPageContent(page, blueprint) {
  const { layout, sections } = page;

  if (layout === "landing") {
    return (
      <div className="space-y-16">
        {sections.map((section, idx) => (
          <div key={idx}>{renderSection(section, idx)}</div>
        ))}
      </div>
    );
  }

  if (layout === "dashboard") {
    return (
      <div>
        <h1 className="text-4xl font-bold text-white mb-8">{page.title}</h1>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {sections.map((section, idx) => (
            <div key={idx}>{renderSection(section, idx)}</div>
          ))}
        </div>
      </div>
    );
  }

  if (layout === "form") {
    return (
      <div className="max-w-2xl mx-auto">
        <h1 className="text-4xl font-bold text-white mb-8 text-center">
          {page.title}
        </h1>
        <div className="space-y-6">
          {sections.map((section, idx) => (
            <div key={idx}>{renderSection(section, idx)}</div>
          ))}
        </div>
      </div>
    );
  }

  if (layout === "list") {
    return (
      <div>
        <h1 className="text-4xl font-bold text-white mb-8">{page.title}</h1>
        <div className="space-y-4">
          {sections.map((section, idx) => (
            <div key={idx}>{renderSection(section, idx)}</div>
          ))}
        </div>
      </div>
    );
  }

  // Default: simple sections
  return (
    <div className="space-y-12">
      <h1 className="text-4xl font-bold text-white mb-8">{page.title}</h1>
      {sections.map((section, idx) => (
        <div key={idx}>{renderSection(section, idx)}</div>
      ))}
    </div>
  );
}

/**
 * Render individual section based on type
 */
function renderSection(section, index) {
  const { type, title, description, fields } = section;

  // Hero section
  if (type === "hero") {
    return (
      <div className="text-center py-16">
        <h1 className="text-6xl font-bold text-white mb-6">{title}</h1>
        {description && (
          <p className="text-xl text-white/70 max-w-2xl mx-auto mb-8">
            {description}
          </p>
        )}
        <button className="px-8 py-4 bg-gradient-to-r from-purple-500 to-pink-500 text-white rounded-full font-bold hover:scale-105 transition-transform shadow-2xl shadow-purple-500/50">
          Get Started
        </button>
      </div>
    );
  }

  // Features grid
  if (type === "features") {
    return (
      <div>
        <h2 className="text-3xl font-bold text-white mb-8 text-center">
          {title || "Features"}
        </h2>
        <div className="grid md:grid-cols-3 gap-6">
          {[1, 2, 3].map((i) => (
            <div
              key={i}
              className="bg-white/5 backdrop-blur-md border border-white/10 rounded-2xl p-6 hover:bg-white/10 transition-all"
            >
              <div className="w-12 h-12 bg-gradient-to-br from-purple-500/20 to-pink-500/20 rounded-xl flex items-center justify-center mb-4 text-2xl">
                ✨
              </div>
              <h3 className="text-lg font-bold text-white mb-2">
                Feature {i}
              </h3>
              <p className="text-white/60 text-sm">
                Amazing functionality that users will love
              </p>
            </div>
          ))}
        </div>
      </div>
    );
  }

  // CTA section
  if (type === "cta") {
    return (
      <div className="bg-gradient-to-br from-purple-600/20 to-pink-600/20 backdrop-blur-md border border-white/20 rounded-3xl p-12 text-center">
        <h2 className="text-4xl font-bold text-white mb-4">
          {title || "Ready to Get Started?"}
        </h2>
        <p className="text-white/80 text-lg mb-8 max-w-2xl mx-auto">
          {description || "Join thousands of users today"}
        </p>
        <button className="px-8 py-4 bg-white text-gray-900 rounded-full font-bold hover:scale-105 transition-transform shadow-xl">
          Start Free Trial
        </button>
      </div>
    );
  }

  // Form section
  if (type === "form" && fields) {
    return (
      <div className="bg-white/5 backdrop-blur-md border border-white/10 rounded-2xl p-8">
        <h3 className="text-2xl font-bold text-white mb-6">{title}</h3>
        <div className="space-y-4">
          {fields.map((field, i) => (
            <div key={i}>
              <label className="block text-white/80 text-sm font-medium mb-2">
                {field.name.charAt(0).toUpperCase() + field.name.slice(1)}
              </label>
              {field.type === "textarea" ? (
                <textarea
                  placeholder={field.placeholder}
                  className="w-full px-4 py-3 bg-white/5 border border-white/10 rounded-lg text-white placeholder-white/40 focus:outline-none focus:ring-2 focus:ring-purple-500/50"
                  rows="3"
                />
              ) : (
                <input
                  type={field.type}
                  placeholder={field.placeholder}
                  className="w-full px-4 py-3 bg-white/5 border border-white/10 rounded-lg text-white placeholder-white/40 focus:outline-none focus:ring-2 focus:ring-purple-500/50"
                />
              )}
            </div>
          ))}
          <button className="w-full px-6 py-3 bg-gradient-to-r from-purple-500 to-pink-500 text-white rounded-lg font-semibold hover:scale-105 transition-transform mt-4">
            Submit
          </button>
        </div>
      </div>
    );
  }

  // Stats section
  if (type === "stats") {
    return (
      <div className="grid grid-cols-3 gap-4">
        {[
          { label: "Total", value: "1,234" },
          { label: "Active", value: "456" },
          { label: "Growth", value: "+23%" },
        ].map((stat, i) => (
          <div
            key={i}
            className="bg-white/5 backdrop-blur-md border border-white/10 rounded-xl p-4 text-center"
          >
            <div className="text-3xl font-bold text-white mb-1">
              {stat.value}
            </div>
            <div className="text-white/60 text-sm">{stat.label}</div>
          </div>
        ))}
      </div>
    );
  }

  // Chart section
  if (type === "chart") {
    return (
      <div className="bg-white/5 backdrop-blur-md border border-white/10 rounded-2xl p-6">
        <h3 className="text-xl font-bold text-white mb-4">
          {title || "Analytics"}
        </h3>
        <div className="h-48 bg-gradient-to-br from-purple-500/10 to-pink-500/10 rounded-xl flex items-end gap-2 p-4">
          {[40, 60, 45, 70, 55, 80, 65].map((height, i) => (
            <div
              key={i}
              className="flex-1 bg-gradient-to-t from-purple-500 to-pink-500 rounded-t"
              style={{ height: `${height}%` }}
            />
          ))}
        </div>
      </div>
    );
  }

  // List section
  if (type === "list") {
    return (
      <div className="bg-white/5 backdrop-blur-md border border-white/10 rounded-2xl p-6">
        <h3 className="text-xl font-bold text-white mb-4">
          {title || "Recent Activity"}
        </h3>
        <div className="space-y-3">
          {[1, 2, 3].map((i) => (
            <div
              key={i}
              className="flex items-center gap-3 p-3 bg-white/5 rounded-lg hover:bg-white/10 transition-colors"
            >
              <div className="w-10 h-10 bg-gradient-to-br from-purple-500/20 to-pink-500/20 rounded-full flex items-center justify-center">
                📌
              </div>
              <div className="flex-1">
                <div className="text-white font-medium text-sm">
                  Item {i}
                </div>
                <div className="text-white/50 text-xs">Just now</div>
              </div>
            </div>
          ))}
        </div>
      </div>
    );
  }

  // Default: Generic card
  return (
    <div className="bg-white/5 backdrop-blur-md border border-white/10 rounded-2xl p-6">
      <h3 className="text-xl font-bold text-white mb-3">
        {title || `Section ${index + 1}`}
      </h3>
      {description && (
        <p className="text-white/60 text-sm">{description}</p>
      )}
    </div>
  );
}
